parameters:
  dependedCacheServiceTag: !php/const Demoniqus\CacheBundle\Interfaces\BundleConstantsModelInterface::CACHE_DEPENDENCY_TAG
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:


  Demoniqus\CacheBundle\Factory\ServicesFactory: ~

  Demoniqus\CacheBundle\Factory\ServicesFactoryInterface: '@Demoniqus\CacheBundle\Factory\ServicesFactory'

  Demoniqus\CacheBundle\DataTransmitter\StringedDataTransmitter: ~
  Demoniqus\CacheBundle\DataTransmitter\HashedDataTransmitter: ~

  Demoniqus\CacheBundle\Interfaces\Common\DataTransmitterInterface: '@Demoniqus\CacheBundle\DataTransmitter\StringedDataTransmitter'

  Demoniqus\CacheBundle\Dependencies\Resolver\DependedCacheServicesResolver:
    arguments:
      $cacheServices: !tagged '%dependedCacheServiceTag%'
  Demoniqus\CacheBundle\Interfaces\DependedCacheServicesResolverInterface: '@Demoniqus\CacheBundle\Dependencies\Resolver\DependedCacheServicesResolver'
